services:
    zero_twitty:
        container_name: 'zero_twitty'
        build: .
        volumes:
            -   .:/app:rw
        restart: always
        environment:
            - ENV_NAME=production